mcminickpt/mcmini

Makefile.in
configure
configure.ac
include/mcmini/MCState.h
src/MCState.cpp
src/launch.c
src/mcmini_private.cpp

* '-v -v' prints full stats; '-v' prints just the thread schedules
* Any deadlock info, etc., will be reprinted after printing "***** Model checking completed! *****\n"
(This fixes a problem where the pinted failure quickly went off screen after the output scrolled to the end.)
* Also: `./configure --enable-debug; CC/CXX can be any comp`

Allow '-v' and '-v -v'; reprint failures at end

---

gdbinit_commands.py
include/mcmini/MCConstants.h
include/mcmini/MCState.h
include/mcmini/mcmini_private.h
src/MCState.cpp
src/mcmini_private.cpp

* Remove PROGRAM_TYPE, MC_TARGET, MC_SCHEDULER, etc.
This is the first commit of several.  The goal is to simplify the core DPOR logic.
* Simplify core DPOR logic using mc_explore_branch()
This defines mc_explore_branch() to replace both mc_initial_trace() and the inline code after `while (nextBranchPoint->hasValue())`
* Minor renaming and removing unneeded functions

Simplify core DPOR logic

---

docs/design/include/mcmini/coordinator/coordinator.hpp
docs/design/include/mcmini/coordinator/model_to_system_map.hpp
docs/design/src/mcmini/coordinator/coordinator.cpp

This commit introduces the `mcmini::coordinator` (hereby referred to as the “coordinator”). The coordinator maintains the correspondence between the model and the process(es) over which McMini has control. The coordinator can move execution forward and backwards in time.
In short, **it is the interface provided to model-checking algorithms**
1. Receive a [notification from the model-checker that execution](https://github.com/maxwellpirtle/mcmini/blob/0fc50818c047fb2c8a360d774ea409fbfec2be34/docs/design/include/mcmini/coordinator/coordinator.hpp#L138-L162) of the specified thread should continue.
This method takes the form of 
```cpp
void execute_runner(runner::runner_id_t id);
```
The model checker [can query the coordinator for its current model] …

Introduce `mcmini::coordinator`

---

docs/design/include/mcmini/model/objects/mutex.hpp
docs/design/include/mcmini/model/objects/thread.hpp
docs/design/include/mcmini/model/pending_transitions.hpp
docs/design/include/mcmini/model/private/serialization.hpp
docs/design/include/mcmini/model/program.hpp
docs/design/include/mcmini/model/state.hpp
docs/design/include/mcmini/model/state/detached_state.hpp
docs/design/include/mcmini/model/state/state_sequence.hpp
docs/design/include/mcmini/model/transition.hpp
docs/design/include/mcmini/model/transition_registry.hpp
docs/design/include/mcmini/model/transitions/mutex/mutex_init.hpp
docs/design/include/mcmini/model/transitions/mutex/mutex_lock.hpp
docs/design/include/mcmini/model/transitions/thread/thread_start.hpp
docs/design/include/mcmini/model/transitions/transition_sequence.hpp
docs/design/include/mcmini/model/visible_object.hpp
docs/design/include/mcmini/model/visible_object_state.hpp
docs/design/src/mcmini/model/detached_state.cpp
docs/design/src/mcmini/model/program.cpp
docs/design/src/mcmini/model/state_sequence.cpp

This PR introduces the components that make up the McMini model. There are several important directories:
- `.` contains the most important headers. These include `visible_object_state.hpp`, `transition.hpp`, `state.hpp`, and other important high-level classes
- The `objects` subdirectory will contain the definitions of McMini visible objects (to be ported from the current codebase in later PRs).  There are two example objects in the directory: [`mutex.hpp`](https://github.com/mcminickpt/mcmini/blob/75a68ec6a2bd61817af4e9b0a2bba017c3dddb5c/docs/design/include/mcmini/model/objects/mutex.hpp#L8) and [`thread.hpp](https://github.com/mcminickpt/mcmini/blob/75a68ec6a2bd61817af4e9b0a2bba017c3dddb5c/docs/design/include/mcmini/model/objects/thread.hpp#L8)
- The `state` subdirectory which contains …

Introduce `mcmini::model::*` and friends

---

docs/design/include/mcmini/model_checking/algorithm.hpp
docs/design/include/mcmini/model_checking/algorithms/classic_dpor.hpp
docs/design/src/mcmini/model_checking/algorithms/classic_dpor.cpp

This PR introduces the model-checking portions of McMini. The `mcmini::model_checking::algorithm` encapsulates the logic of a model-checking algorithm (e.g. DPOR). McMini model-checking algorithms do not interact directly with the underlying processes under McMini's control; rather, execution is mediated via the [`mcmini::coordinator`]( #89).
The model checker instead interacts solely on the model dynamically constructed by the coordinator. A model checking algorithm [can access](https://github.com/maxwellpirtle/mcmini/blob/0fc50818c047fb2c8a360d774ea409fbfec2be34/docs/design/include/mcmini/coordinator/coordinator.hpp#L108C25-L110), for example, the `mcmini::model::program`. For example, DPOR will keep track of its algorithm-specific clock vectors for each element of the transition …

Introduce `mcmini::model_checking::algorithm`

---

src/launch.c

For the flag `--print-at-trace`, we had `cur_arg += 2`.  But this flag does not take an argument.   I'm changing it to `cur_arg += 1`.  Without this, using the flag will segfault.

Bug in flag --print-at-trace: cur_arg += 1

---

src/launch.c

PR #101 had the wrong fix.  The code was correct, but the help message `mcmini -h` was wrong.
This reverts PR #101 and fixes the help message.

Fix mcmini help: [--print-at-trace <num>]

---

src/signals.cpp

gcc warnings:
> src/signals.cpp:66:8: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’
(and two other lines.  Now we do assert on return value to check it.)
Push in PR #102 first, to fix a bug.

Eliminate gcc warnings for 'write()'

---

src/transitions/barrier/MCBarrierEnqueue.cpp
src/transitions/barrier/MCBarrierInit.cpp
src/transitions/barrier/MCBarrierWait.cpp
src/transitions/cond/MCCondBroadcast.cpp
src/transitions/cond/MCCondEnqueue.cpp
src/transitions/cond/MCCondInit.cpp
src/transitions/cond/MCCondSignal.cpp
src/transitions/cond/MCCondWait.cpp
src/transitions/mutex/MCMutexInit.cpp
src/transitions/mutex/MCMutexLock.cpp
src/transitions/mutex/MCMutexUnlock.cpp
src/transitions/rwlock/MCRWLockInit.cpp
src/transitions/rwlock/MCRWLockReaderEnqueue.cpp
src/transitions/rwlock/MCRWLockReaderLock.cpp
src/transitions/rwlock/MCRWLockUnlock.cpp
src/transitions/rwlock/MCRWLockWriterEnqueue.cpp
src/transitions/rwlock/MCRWLockWriterLock.cpp
src/transitions/rwwlock/MCRWWLockInit.cpp
src/transitions/rwwlock/MCRWWLockReaderEnqueue.cpp
src/transitions/rwwlock/MCRWWLockReaderLock.cpp
src/transitions/rwwlock/MCRWWLockUnlock.cpp
src/transitions/rwwlock/MCRWWLockWriter1Enqueue.cpp
src/transitions/rwwlock/MCRWWLockWriter1Lock.cpp
src/transitions/rwwlock/MCRWWLockWriter2Enqueue.cpp
src/transitions/rwwlock/MCRWWLockWriter2Lock.cpp
src/transitions/semaphore/MCSemEnqueue.cpp
src/transitions/semaphore/MCSemInit.cpp
src/transitions/semaphore/MCSemPost.cpp
src/transitions/semaphore/MCSemWait.cpp

For greater clarity, the `STACK` BACKTRACE' now displays in this format, including 'object:' :
thread 2: sem_wait(object:3)
where object:3 means the third object created by McMini.

trace: pthread_XXX(%lu) -> pthread_XXX(object:%lu)

---

src/mcmini_private.cpp

mcmini_private.cpp was printing "traceId" with `trace_pid`.  The user expects the `traceId`, not `trace_pid`.
Also, if the user does `mcmini -p NUM ./a.out`, then we should initialize `traceId` to `NUM` (not to 0).  This PR does that now.

traceId (not trace_pid); Set traceId if '-p NUM'

---

include/mcmini/MCObjectStore.h
include/mcmini/MCSharedTransition.h
include/mcmini/objects/MCConditionVariable.h
include/mcmini/objects/MCRWLock.h
include/mcmini/objects/MCRWWLock.h
include/mcmini/objects/MCSemaphore.h
include/mcmini/transitions/MCTransitionsShared.h
src/MCSharedTransition.cpp
src/transitions/MCTransitionsShared.cpp

When using `-Wall` (invoked by `configure --enable-debug`), the warnings `-Wreorder` and `-Wclass-memaccess` appear repeatedly for g++.
This PR fixes this.
**NOTE:**: fixed both of these warnings by simple casts.  I also include StackOverflow URLs showing how to fix these warnings in a more complicated way using special C++ tricks, but I prefer the casts, since that keeps it simple.

g++: -Wreorder and -Wclass-memaccess warnings fixed for .h files

---

test/deadlock_program/reader_writer/reader_writer_rwlock_deadlock.c

Trivial bug to fix in rwlock deadlock test

Minor bug in main: Requires 4 args, not 5

---

src/mcmini_private.cpp

@maxwellpirtle ,
This needs a trivial review.  It's the same use of `PR_SET_PDEATHSIG` that you had started using -- but in this case, for classic McMini.

Set PR_SET_PDEATHSIG of prctl to reap children

---

src/mcmini_private.cpp

The function `printResults` was already printing `"Number of transitions"`.  We remove the duplicate print in `mccmini_private.cpp`, and also clarify by renaming it:  `"Total number of transitions"`  (It's not just the number for the last trace.)

Remove duplicate print: "Number of transitions"

---

src/launch.c
src/mcmini_private.cpp

This prints the alapsed time at the end, and also prints the number of traces if it is a multiple of 1000, and if at least 10 seconds have elapsed since the last printout.

Print elapsed time at end

---

include/mcmini/MCObjectStore.h
include/mcmini/MCStack.h
include/mcmini/misc/cond/MCConditionVariableArbitraryPolicy.hpp
include/mcmini/misc/cond/MCConditionVariableDefaultPolicy.hpp
include/mcmini/misc/cond/MCConditionVariableGLibcPolicy.hpp
include/mcmini/misc/cond/MCConditionVariablePolicy.hpp
include/mcmini/misc/cond/MCConditionVariableSingleGroupPolicy.hpp
include/mcmini/objects/MCConditionVariable.h
include/mcmini/objects/MCMutex.h
include/mcmini/objects/MCRWLock.h
src/MCStack.cpp
src/mcmini_private.cpp
src/misc/cond/MCConditionVariableArbitraryPolicy.cpp
src/misc/cond/MCConditionVariableDefaultPolicy.cpp
src/misc/cond/MCConditionVariableGLibcPolicy.cpp
src/misc/cond/MCConditionVariableSingleGroupPolicy.cpp
src/objects/MCConditionVariable.cpp
src/transitions/cond/MCCondBroadcast.cpp
src/transitions/cond/MCCondEnqueue.cpp
src/transitions/cond/MCCondInit.cpp
src/transitions/cond/MCCondSignal.cpp
src/transitions/cond/MCCondWait.cpp
src/transitions/mutex/MCMutexLock.cpp
src/transitions/rwlock/MCRWLockInit.cpp
src/transitions/rwlock/MCRWLockReaderLock.cpp
src/transitions/rwlock/MCRWLockWriterLock.cpp

This makes McMini support `PTHREAD_MUTEX_INITIALIZER`, `PTHREAD_COND_INITIALIZER` and  `PTHREAD_RWLOCK_INITIALIZER`.
***To the best of myknowledge, this is now ocmplete and bug-ffree.***
When it discovers `state == undefined`, it sets `state == initialized` (or `state == unlocked` for mutex), and also copies:
`PTHREAD_MUTEX_INITIALIZER`, `PTHREAD_COND_INITIALIZER`, and  `PTHREAD_RWLOCK_INITIALIZER` into the application's corresponding variables of type `pthread_mutex_t`, `pthread_cond_t`, and `pthread_rwlock_t`.
I have now removed my obnoxious comments.
1.  It would be nice to later do a new PR that cleans up things like changing 'auto' to the obvious type.
2.  Alternatively, we could copy this into your new McMini-v2, but that is probably not something that can be done quickly.

Recognize PTHREAD_MUTEX/COND/RWLOCK_INITIALIZER

---

include/mcmini/transitions/cond/MCCondTransition.h
src/transitions/cond/MCCondBroadcast.cpp
src/transitions/cond/MCCondSignal.cpp

In the printed thread trace, if there were no waiters at the time of a `pthread_cond_signal` or `pthread_cond_broadcast`, then the printout of the trace add a warning on the line of that transition: 
> `[No thread waiting on cond; lost wakeup?]`
If you want tot est this, you could try ` test/deadlock_program/simple_cond_deadlock.c`, or many of the bugs that we have for cond vars.

cond_signal/bcast: warn if no waiters; lost wakeup?

---

src/launch.c

Two trivial bugs to fix:
1. First commit: `src/launch.c` has error in which target is thought to be 'mcmini' if it has the same number of letters.
2. Second commit: `src/launch.c` has an error in the use of `strtol()`.
----
**First commit**
> mcmini choose
returns:
> *** McMini being called on 'mcmini'.  This doesn't work. 
because "choose" and "mcmini" have the same number of letters.
This fixes that bug.
----
**Second commit**
An obvious fix in usage of `strtol()`

Fix launch recognizing 'mcmini' as target

---

gdbinit_commands.py

In `mcmini-gdb`, add:
> (gdb) printPendingTransitions
This calls `programState->printNextTransitions()` in the McMini course code.
For a motivation on why this is useful, see this part of the [McMini Sphinx documentation](https://www.khoury.northeastern.edu/home/gene/mcmini-doc/usage/mcmini-advanced.html#analyzing-a-trace-mcmini-print-at-trace-traceseq).

mcmini-gdb: add 'mcmini printPendingTransitions'

---

Makefile.in
gdbinit
gdbinit_commands.py
src/export/rwwlock.c

Minor; easy review
1. Stop compiler warning for `mcmini/export/rwwlock.h` and improve comment
2. Stop building 'mcmini-demo' by default.  `make mcmini-demo` still works if desired.
3. Small number of random improved comments or msg to user

Minor cleanups

---

include/mcmini/MCShared.h
include/mcmini/mc_shared_sem.h

The macro MC_STRUCT_DEF was defined in MCShared.h, and used in mc_shared_sem.h.
The macro is used once only, as:  MC_STRUCT_DEF(mc_shared_sem).
The macro is used to define four types:
> typedef struct mc_shared_sem mc_shared_sem;
> typedef struct mc_shared_sem *mc_shared_sem_t;
> typedef const struct mc_shared_sem *mc_shared_sem_refc;
> typedef struct mc_shared_sem *mc_shared_sem_ref;
The first three types are never used.  The fourth type is now used directly in mc_shared_sem.h, and we remove the remaining text.  This seems to be motivated by the C++ philosophy of hiding all type declarations..  The obfuscation seems to have the purpose that if someone greps for 'mc_shared_sem_ref, they will not find it.
(In general, McMini currently uses five types of semaphores:  mc_shared_sem_ref …

Remove obfuscation from MC_STRUCT_DECL

---

dmtcp/src/lib/dmtcp-callback.c
dmtcp/src/lib/main.c
dmtcp/src/mcmini/mcmini.cpp

We will be in record mode only if the DMTCP McMini plugin, libmcmini, was loaded.  libmcmini will create a strong symbol, dmtcp_mcmini_is_loaded, to override the existing weak symbol, if it has been loaded.

Use a weak symbol to detect if in record mode

---

dmtcp/include/mcmini/model/transitions/condition_variables/condition_variable_enqueue_thread.hpp
dmtcp/src/mcmini/mcmini.cpp

This PR added a missing condition for condition variables at the model side. Without this condition, the model was not able to return that we are in deadlock if the initial state was a deadlock state at the time of restart.

Change in condition variable

---

Makefile_llvm
src/InstrumentMcMiniGlobals.cpp
src/launch.c
src/mcmini_private.cpp
test/data_race.c

The instrumentation pass plugin has been tested
on LLVM 14 and LLVM 18.
Quick test:
```
make -f Makefile_llvm
./mcmini -m5 ./test/data_race_instr
```

LLVM plugin for data race detection
